- config_image: registry.redhat.io/rhosp-rhel8/openstack-cron:16.2
  config_volume: crond
  step_config: include ::tripleo::profile::base::logging::logrotate
- config_image: registry.redhat.io/rhosp-rhel8/openstack-swift-proxy-server:16.2
  config_volume: swift_ringbuilder
  puppet_tags: swift_config,exec,fetch_swift_ring_tarball,extract_swift_ring_tarball,ring_object_device,swift::ringbuilder::create,tripleo::profile::base::swift::add_devices,swift::ringbuilder::rebalance,create_swift_ring_tarball,upload_swift_ring_tarball
  step_config: 'include ::tripleo::profile::base::swift::ringbuilder

    '
- config_image: registry.redhat.io/rhosp-rhel8/openstack-swift-proxy-server:16.2
  config_volume: swift
  puppet_tags: swift_config,swift_container_config,swift_container_sync_realms_config,swift_account_config,swift_object_config,swift_object_expirer_config,rsync::server
  step_config: 'class xinetd() {}

    define xinetd::service($bind='''',$port='''',$server='''',$server_args='''') {}

    include ::tripleo::profile::base::swift::storage'
