oslo_messaging_notify_password: m2529ztmcfrcjtm6vbgsnj679
oslo_messaging_notify_port: 5672
oslo_messaging_notify_scheme: rabbit
oslo_messaging_notify_use_ssl: 'False'
oslo_messaging_notify_user_name: guest
oslo_messaging_rpc_password: m2529ztmcfrcjtm6vbgsnj679
oslo_messaging_rpc_port: 5672
oslo_messaging_rpc_scheme: rabbit
oslo_messaging_rpc_use_ssl: 'False'
oslo_messaging_rpc_user_name: guest
