collectd:
  collectd::plugin::memcached::instances:
    local:
      host: '%{hiera(''memcached::listen_ip_uri'')}'
      port:
      - 11211
  tripleo.collectd.plugins.memcached:
  - memcached
horizon: {}
map_merge:
- null
- rsyslog:
    tripleo_logging_sources_cinder_api:
    - file: /var/log/containers/cinder/cinder-api.log
      tag: openstack.cinder.api
- rsyslog:
    tripleo_logging_sources_placement:
    - file: /var/log/containers/httpd/placement_wsgi_error_ssl.log
      tag: openstack.placement
mysql:
  cinder::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  cinder::db::mysql::dbname: cinder
  cinder::db::mysql::host: 172.17.0.220
  cinder::db::mysql::password: nktlx2pmm27btwjr96bq5plq9
  cinder::db::mysql::user: cinder
  glance::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  glance::db::mysql::dbname: glance
  glance::db::mysql::host: 172.17.0.220
  glance::db::mysql::password: 8sslzm6crwk8bt54q82wjxjjm
  glance::db::mysql::user: glance
  heat::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  heat::db::mysql::dbname: heat
  heat::db::mysql::host: 172.17.0.220
  heat::db::mysql::password: q2tmkksmhmjxfr8w6qpxwvzdm
  heat::db::mysql::user: heat
  keystone::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  keystone::db::mysql::dbname: keystone
  keystone::db::mysql::host: 172.17.0.220
  keystone::db::mysql::password: 2s2hssrfk4hzhvx5zcqhg6l2b
  keystone::db::mysql::user: keystone
  neutron::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  neutron::db::mysql::dbname: ovs_neutron
  neutron::db::mysql::host: 172.17.0.220
  neutron::db::mysql::password: 4bmtgrwlv57snhgvptww2bd8b
  neutron::db::mysql::user: neutron
  nova::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  nova::db::mysql::dbname: nova
  nova::db::mysql::host: 172.17.0.220
  nova::db::mysql::password: 4d8x96p5h8vfll547mfm9ph87
  nova::db::mysql::user: nova
  nova::db::mysql_api::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  nova::db::mysql_api::dbname: nova_api
  nova::db::mysql_api::host: 172.17.0.220
  nova::db::mysql_api::password: 4d8x96p5h8vfll547mfm9ph87
  nova::db::mysql_api::user: nova_api
  placement::db::mysql::allowed_hosts:
  - '%'
  - '%{hiera(''mysql_bind_host'')}'
  placement::db::mysql::dbname: placement
  placement::db::mysql::host: 172.17.0.220
  placement::db::mysql::password: zskxswzgqpn86fqttkf9w2mzw
  placement::db::mysql::user: placement
pacemaker:
  keystone::admin_password: rg8ffsz58cllzcq9b5x4j5ztk
  keystone::endpoint::admin_url: http://192.0.2.220:35357
  keystone::endpoint::internal_url: http://172.17.0.220:5000
  keystone::endpoint::public_url: http://10.0.0.220:5000
  keystone::endpoint::region: regionOne
rabbitmq:
  get_attr:
  - NovaBase
  - role_data
  - service_config_settings
  rabbitmq: null
rsyslog:
  tripleo_logging_sources_cinder_scheduler:
  - file: /var/log/containers/cinder/cinder-scheduler.log
    tag: openstack.cinder.scheduler
  tripleo_logging_sources_cinder_volume:
  - file: /var/log/containers/cinder/cinder-volume.log
    tag: openstack.cinder.volume
  tripleo_logging_sources_glance_api:
  - file: /var/log/containers/glance/api.log
    tag: openstack.glance.api
  tripleo_logging_sources_heat_api:
  - file: /var/log/containers/heat/heat_api.log
    tag: openstack.heat.api
  tripleo_logging_sources_heat_api_cfn:
  - file: /var/log/containers/heat/heat_api_cfn.log
    tag: openstack.heat.api.cfn
  tripleo_logging_sources_heat_engine:
  - file: /var/log/containers/heat/heat-engine.log
    tag: openstack.heat.engine
  tripleo_logging_sources_horizon:
  - file: /var/log/containers/horizon/horizon.log
    tag: openstack.horizon
  tripleo_logging_sources_keystone:
    file: /var/log/containers/keystone/keystone.log
    tag: openstack.keystone
  tripleo_logging_sources_neutron_api:
  - file: /var/log/containers/neutron/server.log
    tag: openstack.neutron.api
  tripleo_logging_sources_nova_api:
  - file: /var/log/containers/nova/nova-api.log
    tag: openstack.nova.api
  tripleo_logging_sources_nova_conductor:
  - file: /var/log/containers/nova/nova-conductor.log
    tag: openstack.nova.conductor
  tripleo_logging_sources_nova_metadata:
  - file: /var/log/containers/nova/nova-metadata-api.log
    tag: openstack.nova.api.metadata
  tripleo_logging_sources_nova_scheduler:
  - file: /var/log/containers/nova/nova-scheduler.log
    tag: openstack.nova.scheduler
  tripleo_logging_sources_nova_vnc_proxy:
  - file: /var/log/containers/nova/nova-novncproxy.log
    tag: openstack.nova.vncproxy
  tripleo_logging_sources_pacemaker:
  - file: /var/log/host/pacemaker/pacemaker.log
    startmsg.regex: ^[a-zA-Z]{3} [0-9]{2} [:0-9]{8}
    tag: system.pacemaker
