step_4:
  logrotate_crond:
    environment:
      KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
    healthcheck:
      test: /usr/share/openstack-tripleo-common/healthcheck/cron
    image: registry.redhat.io/rhosp-rhel8/openstack-cron:16.2
    net: none
    pid: host
    privileged: true
    restart: always
    user: root
    volumes:
    - /etc/hosts:/etc/hosts:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/pki/ca-trust/extracted:/etc/pki/ca-trust/extracted:ro
    - /etc/pki/ca-trust/source/anchors:/etc/pki/ca-trust/source/anchors:ro
    - /etc/pki/tls/certs/ca-bundle.crt:/etc/pki/tls/certs/ca-bundle.crt:ro
    - /etc/pki/tls/certs/ca-bundle.trust.crt:/etc/pki/tls/certs/ca-bundle.trust.crt:ro
    - /etc/pki/tls/cert.pem:/etc/pki/tls/cert.pem:ro
    - /dev/log:/dev/log
    - /etc/puppet:/etc/puppet:ro
    - /var/lib/kolla/config_files/logrotate-crond.json:/var/lib/kolla/config_files/config.json:ro
    - /var/lib/config-data/puppet-generated/crond:/var/lib/kolla/config_files/src:ro
    - /var/log/containers:/var/log/containers:z
