/var/lib/kolla/config_files/logrotate-crond.json:
  command: /usr/sbin/crond -s -n
  config_files:
  - dest: /
    merge: true
    preserve_properties: true
    source: /var/lib/kolla/config_files/src/*
