- config_image: registry.redhat.io/rhosp-rhel8/openstack-iscsid:16.2
  config_volume: iscsid
  puppet_tags: iscsid_config
  step_config: 'include ::tripleo::profile::base::iscsid

    '
  volumes:
  - /etc/iscsi:/etc/iscsi:z
- config_image: registry.redhat.io/rhosp-rhel8/openstack-nova-compute:16.2
  config_volume: nova_libvirt
  puppet_tags: nova_config,nova_paste_api_ini
  step_config: '# TODO(emilien): figure how to deal with libvirt profile.

    # We''ll probably treat it like we do with Neutron plugins.

    # Until then, just include it in the default nova-compute role.

    include tripleo::profile::base::nova::compute::libvirt

    '
- config_image: registry.redhat.io/rhosp-rhel8/openstack-nova-compute:16.2
  config_volume: nova_libvirt
  puppet_tags: libvirtd_config,nova_config,file,libvirt_tls_password
  step_config: 'include tripleo::profile::base::nova::libvirt

    '
- config_image: registry.redhat.io/rhosp-rhel8/openstack-nova-compute:16.2
  config_volume: nova_libvirt
  puppet_tags: libvirtd_config,nova_config,file,libvirt_tls_password
  step_config: 'include ::tripleo::profile::base::nova::compute::libvirt_guests

    '
- config_image: registry.redhat.io/rhosp-rhel8/openstack-nova-compute:16.2
  config_volume: nova_libvirt
  step_config: 'include ::tripleo::profile::base::sshd

    include tripleo::profile::base::nova::migration::target'
- config_image: registry.redhat.io/rhosp-rhel8/openstack-cron:16.2
  config_volume: crond
  step_config: include ::tripleo::profile::base::logging::logrotate
- config_image: registry.redhat.io/rhosp-rhel8/openstack-ovn-controller:16.2
  config_volume: ovn_controller
  puppet_tags: vs_config,exec
  step_config: 'include ::tripleo::profile::base::neutron::agents::ovn

    '
  volumes:
  - /lib/modules:/lib/modules:ro
  - /run/openvswitch:/run/openvswitch:shared,z
  - /etc/sysconfig/modules:/etc/sysconfig/modules
- config_image: registry.redhat.io/rhosp-rhel8/openstack-neutron-server-ovn:16.2
  config_volume: neutron
  puppet_tags: neutron_config,ovn_metadata_agent_config
  step_config: 'include tripleo::profile::base::neutron::ovn_metadata

    '
  volumes:
  - /lib/modules:/lib/modules:ro
  - /run/openvswitch:/run/openvswitch:shared,z
