certmonger_ca: IPA
cinder::cron::db_purge::age: '30'
cinder::cron::db_purge::destination: /var/log/cinder/cinder-rowsflush.log
cinder::cron::db_purge::hour: '0'
cinder::cron::db_purge::maxdelay: '3600'
cinder::cron::db_purge::minute: '1'
cinder::cron::db_purge::month: '*'
cinder::cron::db_purge::monthday: '*'
cinder::cron::db_purge::user: cinder
cinder::cron::db_purge::weekday: '*'
cinder::database_connection: mysql+pymysql://cinder:nktlx2pmm27btwjr96bq5plq9@172.17.0.220/cinder?read_default_file=/etc/my.cnf.d/tripleo.cnf&read_default_group=tripleo
cinder::db::database_db_max_retries: -1
cinder::db::database_max_retries: -1
cinder::glance::glance_api_servers: http://172.17.0.220:9292
cinder::keystone::service_user::auth_type: password
cinder::keystone::service_user::auth_url: http://172.17.0.220:5000/
cinder::keystone::service_user::password: nktlx2pmm27btwjr96bq5plq9
cinder::keystone::service_user::project_name: service
cinder::keystone::service_user::send_service_user_token: true
cinder::logging::debug: false
cinder::nova::auth_type: password
cinder::nova::auth_url: http://172.17.0.220:5000/
cinder::nova::interface: admin
cinder::nova::password: 4d8x96p5h8vfll547mfm9ph87
cinder::nova::project_name: service
cinder::rabbit_heartbeat_timeout_threshold: 60
cinder::rpc_response_timeout: 60
cinder::storage_availability_zone: nova
snmp::agentaddress:
- udp:161
- udp6:[::1]:161
snmp::snmpd_options: -LS0-5d
tripleo::chrony::firewall_rules:
  105 ntp:
    dport: 123
    proto: udp
tripleo::cinder_volume::firewall_rules:
  120 iscsi initiator:
    dport: 3260
tripleo::firewall::manage_firewall: true
tripleo::firewall::purge_firewall_rules: false
tripleo::packages::enable_install: true
tripleo::profile::base::cinder::volume::cinder_enable_iscsi_backend: true
tripleo::profile::base::cinder::volume::cinder_enable_nfs_backend: false
tripleo::profile::base::cinder::volume::cinder_enable_rbd_backend: false
tripleo::profile::base::cinder::volume::cinder_volume_cluster: ''
tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_address: '%{hiera(''storage'')}'
tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_helper: lioadm
tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_protocol: iscsi
tripleo::profile::base::cinder::volume::nfs::cinder_nas_secure_file_operations: 'False'
tripleo::profile::base::cinder::volume::nfs::cinder_nas_secure_file_permissions: 'False'
tripleo::profile::base::cinder::volume::nfs::cinder_nfs_mount_options: context=system_u:object_r:container_file_t:s0
tripleo::profile::base::cinder::volume::nfs::cinder_nfs_servers: []
tripleo::profile::base::cinder::volume::nfs::cinder_nfs_snapshot_support: true
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_ceph_conf: /etc/ceph/ceph.conf
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_extra_pools: []
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_flatten_volume_from_snapshot: false
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_pool_name: volumes
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_secret_uuid: 6dad8f2f-02b5-41b7-b876-54d363f4bac8
tripleo::profile::base::cinder::volume::rbd::cinder_rbd_user_name: openstack
tripleo::profile::base::database::mysql::client::enable_ssl: false
tripleo::profile::base::database::mysql::client::mysql_client_bind_address: '%{hiera(''internal_api'')}'
tripleo::profile::base::database::mysql::client::ssl_ca: /etc/ipa/ca.crt
tripleo::profile::base::logging::logrotate::dateext: false
tripleo::profile::base::logging::logrotate::maxsize: 10M
tripleo::profile::base::logging::logrotate::purge_after_days: '14'
tripleo::profile::base::logging::logrotate::rotate: '14'
tripleo::profile::base::logging::logrotate::rotation: daily
tripleo::profile::base::lvm::enable_udev: false
tripleo::profile::base::snmp::snmpd_password: k5njxv4lw7pcxhsd55bq4wzs
tripleo::profile::base::snmp::snmpd_user: ro_snmp_user
tripleo::profile::base::sshd::bannertext: ''
tripleo::profile::base::sshd::motd: ''
tripleo::profile::base::sshd::options:
  AcceptEnv:
  - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  - LC_IDENTIFICATION LC_ALL LANGUAGE
  - XMODIFIERS
  AuthorizedKeysFile: .ssh/authorized_keys
  ChallengeResponseAuthentication: 'no'
  GSSAPIAuthentication: 'yes'
  GSSAPICleanupCredentials: 'no'
  HostKey:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
  Subsystem: sftp  /usr/libexec/openssh/sftp-server
  SyslogFacility: AUTHPRIV
  UseDNS: 'no'
  UsePAM: 'yes'
  UsePrivilegeSeparation: sandbox
  X11Forwarding: 'yes'
tripleo::profile::base::sshd::password_authentication: 'no'
tripleo::snmp::firewall_rules:
  124 snmp 192.0.2.0/24:
    dport: 161
    proto: udp
    source: 192.0.2.0/24
tripleo::sshd::firewall_rules:
  003 accept ssh from all:
    dport: 22
    extras:
      ensure: absent
    proto: tcp
tripleo::tripleo_firewall::firewall_rules:
  003 accept ssh from ctlplane subnet 192.0.2.0/24:
    dport: 22
    proto: tcp
    source: 192.0.2.0/24
tripleo::trusted_cas::ca_map: {}
