- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud:Controller"
    deploy_target_host: "overcloud"
- hosts: Controller
  name: Run pre-upgrade rolling tasks
  serial:  1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  tasks:
    - include_tasks: pre_upgrade_rolling_steps_tasks.yaml
      with_sequence: start=0 end=0
      loop_control:
        loop_var: step
- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud:Compute"
    deploy_target_host: "overcloud"
- hosts: Compute
  name: Run pre-upgrade rolling tasks
  serial:  1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  tasks:
    - include_tasks: pre_upgrade_rolling_steps_tasks.yaml
      with_sequence: start=0 end=0
      loop_control:
        loop_var: step
- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud:BlockStorage"
    deploy_target_host: "overcloud"
- hosts: BlockStorage
  name: Run pre-upgrade rolling tasks
  serial:  1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  tasks:
    - include_tasks: pre_upgrade_rolling_steps_tasks.yaml
      with_sequence: start=0 end=0
      loop_control:
        loop_var: step
- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud:ObjectStorage"
    deploy_target_host: "overcloud"
- hosts: ObjectStorage
  name: Run pre-upgrade rolling tasks
  serial:  1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  tasks:
    - include_tasks: pre_upgrade_rolling_steps_tasks.yaml
      with_sequence: start=0 end=0
      loop_control:
        loop_var: step
- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud:CephStorage"
    deploy_target_host: "overcloud"
- hosts: CephStorage
  name: Run pre-upgrade rolling tasks
  serial:  1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: yes
  tasks:
    - include_tasks: pre_upgrade_rolling_steps_tasks.yaml
      with_sequence: start=0 end=0
      loop_control:
        loop_var: step
